<?xml version="1.0" encoding="UTF-8"?><testrun name="hanto.Test.studentThhughes.common.moveValidator" project="Hanto2016thhughes" tests="5" started="5" failures="0" errors="1" ignored="0">
  <testsuite name="hanto.Test.studentThhughes.common.moveValidator.PieceValidatorTest" time="0.0">
    <testcase name="testValidatorWithItemsInListAndINValidMove" classname="hanto.Test.studentThhughes.common.moveValidator.PieceValidatorTest" time="0.0"/>
    <testcase name="testValidatorWithItemsInListAndValidMove" classname="hanto.Test.studentThhughes.common.moveValidator.PieceValidatorTest" time="0.0"/>
    <testcase name="testValidatorWithNoArgs" classname="hanto.Test.studentThhughes.common.moveValidator.PieceValidatorTest" time="0.0"/>
    <testcase name="testValidatorWithEmptyList" classname="hanto.Test.studentThhughes.common.moveValidator.PieceValidatorTest" time="0.0"/>
    <testcase name="testFailureMessage" classname="hanto.Test.studentThhughes.common.moveValidator.PieceValidatorTest" time="0.0">
      <error>java.lang.Exception: Unexpected exception, expected&lt;hanto.common.HantoException&gt; but was&lt;java.lang.Error&gt;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type HantoException

	at hanto.Test.studentThhughes.common.moveValidator.PieceValidatorTest.testFailureMessage(PieceValidatorTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 15 more

</error>
    </testcase>
  </testsuite>
</testrun>
